<?hh
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

$sequence = Vector{1, 2};
$penultimate = 1;

while (($penultimate + $sequence->lastValue()) <= 4000000) {
  $next = $penultimate + $sequence->lastValue();
  $penultimate = $sequence->lastValue();
  $sequence->add($next);
}

$evenSequence = $sequence->filter($el ==> $el % 2 == 0);

echo array_sum($evenSequence);
